In [1]:
aList = [0,1,2,3,4,5]
type(aList)

list

In [2]:
listList = [3,['4','5','6'],7.7,[8,9,10]]
type(listList)

list

In [3]:
listList

[3, ['4', '5', '6'], 7.7, [8, 9, 10]]

In [4]:
aList = [0,1,2,3,4,5]
sList = ['0','1','2','3','4','5']

aList + sList

[0, 1, 2, 3, 4, 5, '0', '1', '2', '3', '4', '5']

In [5]:
aList * 3

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]

In [6]:
sList * 2

['0', '1', '2', '3', '4', '5', '0', '1', '2', '3', '4', '5']

In [7]:
import numpy as np
aList_np = np.array(aList)

print(aList)
print(aList_np)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


In [8]:
aList_np * 3

array([ 0,  3,  6,  9, 12, 15])

In [9]:
aList_np + 3

array([3, 4, 5, 6, 7, 8])

In [10]:
aList + [3]

[0, 1, 2, 3, 4, 5, 3]

In [11]:
s = 'Daniel'
for i,letter in enumerate(s):
    print(i,letter)

0 D
1 a
2 n
3 i
4 e
5 l


In [12]:
for item in range(len(listList)):
    print(f'List element {item} is {item} and is of type {type(item)}')

List element 0 is 0 and is of type <class 'int'>
List element 1 is 1 and is of type <class 'int'>
List element 2 is 2 and is of type <class 'int'>
List element 3 is 3 and is of type <class 'int'>


In [13]:
for idx,item in enumerate(listList):
    print(f'List element {idx} is {item} and is of type {type(item)}')

List element 0 is 3 and is of type <class 'int'>
List element 1 is ['4', '5', '6'] and is of type <class 'list'>
List element 2 is 7.7 and is of type <class 'float'>
List element 3 is [8, 9, 10] and is of type <class 'list'>


In [18]:
for idx,item in enumerate(listList):
    t = str(type(item))[8:]
    apost = t.find("'")
    print(f'List element {idx} is {item} and is of type {t[:apost]}')

List element 0 is 3 and is of type int
List element 1 is ['4', '5', '6'] and is of type list
List element 2 is 7.7 and is of type float
List element 3 is [8, 9, 10] and is of type list


In [7]:
li1 = [1,2,3,4,5,6,7,8,9,10]
print(type(li1))
li1[-1]

<class 'list'>


10

In [8]:
# slicing to print out the first N elements
N = 2
li1[:N]

[1, 2]

In [9]:
n = 1
k = 9
li1[n:k]

[2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
import sympy as sym
from IPython.display import display,Math
x = sym.symbols('x')

e1 = 2*x + x*(4-6*x) + x
e2 = -x * (2/x + 4/x**2) + (4+x)/(4*x)
e3 = (x+3)*(x-3)*x*(1/(9*x))

expr = [e1,e2,e3]

for expri in expr:
    display(Math('%s \\quad \\Longleftrightarrow \\quad %s' %(sym.latex(expri),sym.latex(sym.expand(expri)))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>