In [1]:
import sympy as sym
import numpy as np
from IPython.display import display,Math

In [2]:
A = np.array([ [1,2],[3,4] ])

print(A)
display(Math(sym.latex(sym.sympify(A))))

[[1 2]
 [3 4]]


<IPython.core.display.Math object>

In [5]:
mat = np.zeros([4,6])
mat[0,1] = 2
mat[2,4] = 7
mat

array([[0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
numrange = range(0,4)

for rowi in numrange:
    for coli in numrange:
        mat[rowi, coli] = (-1)**(rowi+coli)

mat

array([[ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.],
       [ 1., -1.,  1., -1.,  7.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.]])

In [13]:
from sympy.abc import x,y

fn = (4+x)*(2-y)
mat_range = range(0,3)
mat = np.zeros([len(mat_range),len(mat_range)])

for rowi in mat_range:
    for coli in mat_range:
        mat[rowi,coli] = fn.subs({x:rowi,y:coli})

display(Math(sym.latex(sym.sympify(mat))))

<IPython.core.display.Math object>

In [17]:
mul_range = range(0,10)
mat = np.zeros(([len(mul_range),len(mul_range)]),dtype=int)

for i in mul_range:
    for j in mul_range:
        mat[i,j] = (i+1)*(j+1)

display(Math(sym.latex(sym.sympify(mat))))

<IPython.core.display.Math object>